# WhatATheme
# markdown: kramdown

# URL of the Site
url: 'https://alvaroramajo.com'
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: 

encoding: UTF-8

# Title of the Site
title: Álvaro Ramajo
# Description of the Site
description: Personal website
# URL of Image of the Site
site-image: /assets/images/meta.jpg
# Keywords of the Site
site-keywords: Site, Template, Theme
# URL for the Image of custom Favicon
favicon-url: 

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
# heroimage: https://images.pexels.com/photos/220444/pexels-photo-220444.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940
heroimage: /assets/images/hero-image.webp

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email:
facebook_username:
twitter_username:
instagram_username:
linkedin_username: alvaro-ramajo-ballester
github_username: ramajoballester
youtube_channel_id:
reddit_username:
behance_username:
dribbble_username:
spotify_username:
google_scholar_username: UVJ6OqQAAAAJ
orcid_username: 0000-0001-9425-9408
publons_username: HKE-3214-2023
scopus_username: 58035287800

# Google Analytics
google-analytics:

# Disqus
# disqus-shortname: thedevslot
disqus-shortname: /

# Name of the Author
author-name: TheDevsLot
# URL for the Image of the Author
author-image: /assets/images/ramajo_lowq.png
# 60 Words About the Author
author-about: "Lorem ipsum dolor sit amet, \nconsectetur adipiscing elit. Suspendisse eget pharetra velit, dapibus bibendum ex. Maecenas vitae laoreet mauris, ac luctus metus. Aliquam luctus velit vel ipsum feugiat, vel venenatis mauris hendrerit. Sed at vulputate sapien, eget vehicula dolor. Aliquam volutpat pulvinar neque sit amet sodales.
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse eget pharetra velit, dapibus bibendum ex. Maecenas vitae laoreet mauris, ac luctus metus. Aliquam luctus velit vel ipsum feugiat, vel venenatis mauris hendrerit. Sed at vulputate sapien, eget vehicula dolor. Aliquam volutpat pulvinar neque sit amet sodales.

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse eget pharetra velit, dapibus bibendum ex. Maecenas vitae laoreet mauris, ac luctus metus. Aliquam luctus velit vel ipsum feugiat, vel venenatis mauris hendrerit. Sed at vulputate sapien, eget vehicula dolor. Aliquam volutpat pulvinar neque sit amet sodales.
arstrt"
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://github.com/thedevslot

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "news/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
